### ISSUE TITLE
Fix occasional ZeroDivisionError

### ISSUE THREAD

**Issue by Gamma17** [Gamma17/machine_learning#2]
patrick@Beatrice:~/projects/machine_learning$ python run_kmeans.py mlearn.data.iris_numeric 3 100
Traceback (most recent call last):
  File "run_kmeans.py", line 13, in <module>
    kmeans.run()
  File "/home/patrick/projects/machine_learning/mlearn/clustering/kmeans.py", line 90, in run
    self.update_means()
  File "/home/patrick/projects/machine_learning/mlearn/clustering/kmeans.py", line 57, in update_means
    self.clusters[i].mean = [x / y for x, y in zip(means[i], [counts[i]] * nvalues)]
ZeroDivisionError: integer division or modulo by zero

**Comment by Gamma17** [comment]
Fixed error.
